# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.05.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.05 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.05.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.05 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.15.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.15 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.15.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.15 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.5.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.5 --sample_method random


# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.05.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.05 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.1.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.1 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.15.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.15 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.2.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.2 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.25.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.25 --sample_method euclidean

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.2.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.2 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.2.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.2 --sample_method random


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.1.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.2.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method euclidean


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_0.1.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method heatmap_emd_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_0.15.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method heatmap_emd_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_0.2.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method heatmap_emd_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_0.25.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method heatmap_emd_tree


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.1.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method heatmap_emd_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.15.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method heatmap_emd_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.2.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method heatmap_emd_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.25.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method heatmap_emd_tree_prune



# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.1.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method heatmap_emd_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.15.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method heatmap_emd_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.2.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method heatmap_emd_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.25.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method heatmap_emd_tree_prune


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  euclidean_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method euclidean_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  euclidean_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method euclidean_tree


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method euclidean_tree_prune



# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.02.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.02 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.04.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.04 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.06.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.06 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.08.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.08 --sample_method random

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.02.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.02 --sample_method euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.04.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.04 --sample_method euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.06.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.06 --sample_method euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.08.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.08 --sample_method euclidean_tree_prune

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.1.yaml --batch_size=2 --epochs=20  --pretrained_model  /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.2.yaml --batch_size=2 --epochs=20  --pretrained_model  /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method random


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_divergence_0.1.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method divergence
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_divergence_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method divergence
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_divergence_0.2.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method divergence
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_divergence_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method divergence



# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.05.yaml --batch_size=2 --epochs=10  --pretrained_model ../output/nuscenes_models/centerpoint/centerpoint_0.1_pretrain/default/ckpt/checkpoint_epoch_15.pth --sample_rate 0.05 --sample_method loss
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.1.yaml --batch_size=2 --epochs=20  --pretrained_model ../output/nuscenes_models/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method loss
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model ../output/nuscenes_models/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method loss
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.2.yaml --batch_size=2 --epochs=20  --pretrained_model ../output/nuscenes_models/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method loss
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model ../output/nuscenes_models/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method loss

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method loss
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_divergence_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method divergence
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method euclidean_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_0.3.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method heatmap_emd_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.3.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method heatmap_emd_tree_prune

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_random_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method random
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method loss
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_divergence_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method divergence
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method euclidean_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_tree_prune_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method euclidean_tree_prune
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_0.35.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method heatmap_emd_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_tree_prune_0.35.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method heatmap_emd_tree_prune




# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.1.yaml --batch_size=2 --epochs=25  --pretrained_model  /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method heatmap_emd
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.15.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method heatmap_emd
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.2.yaml --batch_size=2 --epochs=25  --pretrained_model  /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method heatmap_emd
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.25.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method heatmap_emd

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.1.yaml --batch_size=2 --ckpt  ../output/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.1/default/ckpt/latest_model.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.15.yaml --batch_size=2 --ckpt ../output/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.15/default/ckpt/latest_model.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.2.yaml --batch_size=2 --ckpt  ../output/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.2/default/ckpt/latest_model.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.25.yaml --batch_size=2 --ckpt ../output/nuscenes_models/centerpoint/centerpoint_heatmap_emd_0.25/default/ckpt/latest_model.pth
# bash scripts/dist_test.sh 1 --batch_size=1 --cfg_file  cfgs/nuscenes_models/cbgs_dyn_pp_centerpoint.yaml --ckpt ../checkpoints/cbgs_pp_centerpoint_nds6070.pth 

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.1.yaml --batch_size=2 --ckpt /data/checkpoints/nuscenes_output/centerpoint/centerpoint_loss_0.1/default/ckpt/checkpoint_epoch_20.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.15.yaml --batch_size=2 --ckpt /data/checkpoints/nuscenes_output/centerpoint/centerpoint_loss_0.15/default/ckpt/checkpoint_epoch_20.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.2.yaml --batch_size=2 --ckpt /data/checkpoints/nuscenes_output/centerpoint/centerpoint_loss_0.2/default/ckpt/checkpoint_epoch_20.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_loss_0.25.yaml --batch_size=2 --ckpt /data/checkpoints/nuscenes_output/centerpoint/centerpoint_loss_0.25/default/ckpt/checkpoint_epoch_20.pth

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_random_0.1.yaml --batch_size=2 --ckpt  /data/checkpoints/nuscenes_output/centerpoint/centerpoint_random_0.1/default/ckpt/checkpoint_epoch_20.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_random_0.15.yaml --batch_size=2 --ckpt /data/checkpoints/nuscenes_output/centerpoint/centerpoint_random_0.15/default/ckpt/checkpoint_epoch_20.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_random_0.2.yaml --batch_size=2 --ckpt  /data/checkpoints/nuscenes_output/centerpoint/centerpoint_random_0.2/default/ckpt/checkpoint_epoch_20.pth
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/nuscenes_models/centerpoint/centerpoint_random_0.25.yaml --batch_size=2 --ckpt /data/checkpoints/nuscenes_output/centerpoint/centerpoint_random_0.25/default/ckpt/checkpoint_epoch_20.pth



# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.4.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method random_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_random_0.5.yaml --batch_size=2 --epochs=27  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method random_scene_even


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centelrpoint_loss_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.4.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method loss_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_loss_0.5.yaml --batch_size=2 --epochs=27  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method loss_scene_even

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.4.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method divergence_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_divergence_0.5.yaml --batch_size=2 --epochs=27  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method divergence_scene_even

export CUDA_LAUNCH_BLOCKING=1
export TORCH_SHOW_CPP_STACKTRACES=1
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.4.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method scene_even_euclidean
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_euclidean_tree_0.5.yaml --batch_size=2 --epochs=27  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method scene_even_euclidean

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  scene_even_heatmap
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method scene_even_heatmap
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  scene_even_heatmap
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method scene_even_heatmap
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method scene_even_heatmap
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method scene_even_heatmap
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.4.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method scene_even_heatmap


# export CUDA_LAUNCH_BLOCKING=1
# export TORCH_SHOW_CPP_STACKTRACES=1
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_heatmap_emd_tree_0.5.yaml --batch_size=2 --epochs=35  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method scene_even_heatmap

# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.1.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.15.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.2.yaml  --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.25.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.3.yaml --batch_size=2 --epochs=25  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.35.yaml --batch_size=2 --epochs=30  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.4.yaml --batch_size=2 --epochs=30  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method heatmap_scene_tree
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/centerpoint_heatmap_scene_emd_tree_0.4.yaml --batch_size=2 --epochs=30  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method heatmap_scene_tree


# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/baseline/centerpoint_fedcs_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1  --sample_method  baseline_fedcs
# # python train.py --cfg_file cfgs/nuscenes_models/centerpoint/baseline/centerpoint_fedcs_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method  baseline_fedcs
# # python train.py --cfg_file cfgs/nuscenes_models/centerpoint/baseline/centerpoint_fedcs_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2  --sample_method  baseline_fedcs
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/baseline/centerpoint_fedcs_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method  baseline_fedcs
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/baseline/centerpoint_fedcs_0.3.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3  --sample_method  baseline_fedcs





# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.08.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.08 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.06.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.06 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.04.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.02.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.02 --sample_method random

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.08.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.08 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.06.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.06 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.04.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.02.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.02 --sample_method loss

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.08.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.08 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.06.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.06 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.04.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.02.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.02 --sample_method euclidean

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.08.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.08 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.06.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.06 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.04.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.02.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.02 --sample_method divergence



# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_median_0.08.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.08 --sample_method loss_median
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_median_0.06.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.06 --sample_method loss_median
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_median_0.04.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method loss_median
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_median_0.02.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.02 --sample_method loss_median

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_median_0.08.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.08 --sample_method divergence_median
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_median_0.06.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.06 --sample_method divergence_median
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_median_0.04.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method divergence_median
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_median_0.02.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.02 --sample_method divergence_median


# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_random_0.02.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_random_0.02/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_random_0.04.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_random_0.04/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_random_0.06.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_random_0.06/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_random_0.08.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_random_0.08/default/ckpt/checkpoint_epoch_15.pth 

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.02.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_0.02/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.04.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_0.04/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.06.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_0.06/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.08.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_0.08/default/ckpt/checkpoint_epoch_15.pth 

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.02.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_euclidean_0.02/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.04.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_euclidean_0.04/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.06.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_euclidean_0.06/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.08.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_euclidean_0.08/default/ckpt/checkpoint_epoch_15.pth 

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.02.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_0.02/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.04.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_0.04/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.06.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_0.06/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.08.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_0.08/default/ckpt/checkpoint_epoch_15.pth 

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.02.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_median_0.02/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.04.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_median_0.04/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.06.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_median_0.06/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_loss_0.08.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_loss_median_0.08/default/ckpt/checkpoint_epoch_15.pth 

# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.02.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_median_0.02/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.04.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_median_0.04/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.06.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_median_0.06/default/ckpt/checkpoint_epoch_15.pth 
# bash scripts/dist_test.sh 1 --cfg_file  cfgs/kitti_models/centerpoint/centerpoint_divergence_0.08.yaml --batch_size=2 --ckpt /home/xiaoyu/experiments/OpenPCDet/output/kitti_models/centerpoint/centerpoint_divergence_median_0.08/default/ckpt/checkpoint_epoch_15.pth 



# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_500_pretrain.yaml --batch_size=2 --epochs=30 --sample_rate 0.1 --sample_method pretrain

# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_random_0.1.yaml  --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1  --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_random_0.15.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_random_0.2.yaml  --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2  --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_random_0.25.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method random

# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_loss_0.1.yaml  --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth  --sample_rate 0.1 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_loss_0.15.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_loss_0.2.yaml  --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth  --sample_rate 0.2 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_loss_0.25.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method loss

# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_euclidean_0.1.yaml  --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_euclidean_0.15.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_euclidean_0.2.yaml  --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_euclidean_0.25.yaml --batch_size=2 --epochs=15 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method euclidean

# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_divergence_0.1.yaml  --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_divergence_0.15.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_divergence_0.2.yaml  --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint_car_only/centerpoint_divergence_0.25.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint_car_only/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method divergence


# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.1.yaml  --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1  --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.15.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.2.yaml  --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2  --sample_method random
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_random_0.25.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method random

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.1.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth  --sample_rate 0.1 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.15.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.2.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth  --sample_rate 0.2 --sample_method loss
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_loss_0.25.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method loss

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.1.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.15.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method euclidean
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.2.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2 --sample_method euclideanexperiments/OpenPCDet/tools/cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.04.yaml experiments/OpenPCDet/tools/cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.06.yaml experiments/OpenPCDet/tools/cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.08.yaml experiments/OpenPCDet/tools/cfgs/nuscenes_models/centerpoint/centerpoint_euclidean_0.02.yaml
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_euclidean_0.25.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method euclidean

# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.1.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.15.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.2.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2 --sample_method divergence
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_divergence_0.25.yaml --batch_size=2 --epochs=20 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method divergence







# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_heatmap_emd_0.04.yaml --batch_size=2 --epochs=30 --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.04 --sample_method heatmap_emd
# python heatmap_compare.py
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_heatmap_emd_0.1.yaml --batch_size=2 --epochs=30  --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.1   --sample_method heatmap_emd
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_heatmap_emd_0.15.yaml --batch_size=2 --epochs=30  --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.15 --sample_method heatmap_emd
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_heatmap_emd_0.2.yaml --batch_size=2 --epochs=30  --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.2   --sample_method heatmap_emd
# python train.py --cfg_file cfgs/kitti_models/centerpoint/centerpoint_heatmap_emd_0.25.yaml --batch_size=2 --epochs=30  --pretrained_model ../output/kitti_models/centerpoint/centerpoint_500_pretrain/default/ckpt/checkpoint_epoch_30.pth --sample_rate 0.25 --sample_method heatmap_emd


export CUDA_LAUNCH_BLOCKING=1
export TORCH_SHOW_CPP_STACKTRACES=1
python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.1.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.1 --sample_method  uniform_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.15.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.15 --sample_method uniform_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.2.yaml  --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.2 --sample_method  uniform_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.25.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.25 --sample_method uniform_scene_even
export CUDA_LAUNCH_BLOCKING=1
export TORCH_SHOW_CPP_STACKTRACES=1
python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.3.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.3 --sample_method   uniform_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.35.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.35 --sample_method uniform_scene_even
# python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.4.yaml --batch_size=2 --epochs=20  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.4 --sample_method   uniform_scene_even
export CUDA_LAUNCH_BLOCKING=1
export TORCH_SHOW_CPP_STACKTRACES=1
python train.py --cfg_file cfgs/nuscenes_models/centerpoint/scene_base/centerpoint_uniform_0.5.yaml --batch_size=2 --epochs=27  --pretrained_model /data/checkpoints/nuscenes_output/centerpoint/centerpoint_0.1_pretrain/default/ckpt/latest_model.pth --sample_rate 0.5 --sample_method   uniform_scene_even
